# -*- coding: utf-8 -*-
"""DSA_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLZKd4K25SBqMZXgqyRLh_5o-goOvIyI
"""

!pip install accelerate peft bitsandbytes transformers trl

import torch
from datasets import load_dataset, Dataset
from peft import LoraConfig, AutoPeftModelForCausalLM
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments
from trl import SFTTrainer
import os

dataset = load_dataset("json", data_files=r"D:\DSA project\formatted_tinyllama_dataset.json")

# Model and output paths
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
output_model = "tinyllama-improm2prompt-v1"

from google.colab import files
uploaded = files.upload()

dataset = load_dataset("json", data_files="formatted_tinyllama_dataset.json")

model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
output_model = "tinyllama-improm2prompt-v1"

def get_model_and_tokenizer(model_id):
    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
    tokenizer.pad_token = tokenizer.eos_token

    # 4-bit quantization setup for QLoRA
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,  # better stability
        bnb_4bit_use_double_quant=True,
    )

    # Load model with quantization
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
    )

    # Configuration tweaks for fine-tuning
    model.config.use_cache = False
    model.config.pretraining_tp = 1

    # Enable gradient checkpointing to save memory
    model.gradient_checkpointing_enable()

    return model, tokenizer

model, tokenizer = get_model_and_tokenizer(model_id)

print("Tokenizer loaded ✅")
print("Pad token:", tokenizer.pad_token)
print("Vocabulary size:", tokenizer.vocab_size)

peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj"],  # focus LoRA on attention
)

from transformers import TrainingArguments

training_arguments = TrainingArguments(
    output_dir=output_model,
    per_device_train_batch_size=4,       # safer for Colab GPUs
    gradient_accumulation_steps=2,       # effective batch size = 8
    optim="paged_adamw_32bit",
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    num_train_epochs=3,
    logging_steps=10,
    save_strategy="epoch",
    save_total_limit=1,
    fp16=True,                           # mixed precision
    report_to="none",
)

import trl
print(trl.__version__)

!pip install -U -q \
  transformers==4.44.2 \
  trl==0.9.6 \
  peft==0.10.0 \
  accelerate==0.33.0 \
  bitsandbytes==0.43.1

import torch, transformers, trl, peft, accelerate, bitsandbytes
print("Torch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("TRL:", trl.__version__)
print("PEFT:", peft.__version__)
print("Accelerate:", accelerate.__version__)
print("BitsAndBytes:", bitsandbytes.__version__)

import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments
from peft import LoraConfig
from trl import SFTTrainer

!pip uninstall -y bitsandbytes triton
!pip install -U bitsandbytes==0.43.3 triton==2.3.0

import bitsandbytes as bnb
print("BitsAndBytes GPU available:", bnb.cuda_available)

!pip uninstall -y bitsandbytes
!rm -rf /usr/local/lib/python3.*/dist-packages/bitsandbytes
!rm -rf /usr/lib/python3.*/dist-packages/bitsandbytes

!pip install bitsandbytes-gpu

!pip install -U bitsandbytes-cuda118==0.43.3

!pip uninstall -y bitsandbytes
!rm -rf /usr/local/lib/python3*/dist-packages/bitsandbytes
!rm -rf /usr/lib/python3*/dist-packages/bitsandbytes

!pip uninstall -y bitsandbytes
!rm -rf /usr/local/lib/python*/dist-packages/bitsandbytes*
!rm -rf /usr/lib/python*/dist-packages/bitsandbytes*

!pip install bitsandbytes==0.43.3

import torch, bitsandbytes as bnb
print("Torch CUDA available:", torch.cuda.is_available())

try:
    from bitsandbytes import cuda_setup
    print(cuda_setup.main_check())
except Exception as e:
    print("bitsandbytes check error:", e)

!nvidia-smi

!pip install -U bitsandbytes==0.43.3

import torch, bitsandbytes as bnb
print("Torch CUDA available:", torch.cuda.is_available())

!pip uninstall -y bitsandbytes triton
!rm -rf /usr/local/lib/python3*/dist-packages/bitsandbytes*
!rm -rf /usr/local/lib/python3*/dist-packages/triton*

!pip install bitsandbytes==0.43.3 triton==3.0.0

import torch, bitsandbytes as bnb
print("Torch CUDA available:", torch.cuda.is_available())

try:
    import bitsandbytes.cuda_setup as cuda_setup
    print(cuda_setup.main_check())
except Exception as e:
    print("bitsandbytes check error:", e)

import torch
from transformers import BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(load_in_4bit=True)
print("BitsAndBytes 4-bit enabled:", bnb_config.load_in_4bit)
print("GPU device:", torch.cuda.get_device_name(0))

# === Core imports for LoRA fine-tuning ===
from peft import LoraConfig
from trl import SFTTrainer
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from datasets import load_dataset
import torch

!pip uninstall -y torch torchvision torchaudio
!pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1
!pip install -U transformers==4.44.2 trl==0.9.6 peft==0.10.0 accelerate==0.33.0 bitsandbytes==0.43.3

import torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig, TrainingArguments
from peft import LoraConfig
from trl import SFTTrainer

print("Torch version:", torch.__version__)
print("Transformers:", __import__("transformers").__version__)
print("GPU available:", torch.cuda.is_available())

# === Dataset ===
from datasets import load_dataset

dataset = load_dataset("json", data_files="formatted_tinyllama_dataset.json")
dataset = dataset["train"].train_test_split(test_size=0.1, seed=42)

# === Model + Tokenizer ===
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch

model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
output_model = "tinyllama-improm2prompt-v1"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
)
model.config.use_cache = False
model.config.pretraining_tp = 1

# === LoRA Configuration ===
from peft import LoraConfig

peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj"],
)

# === Training Arguments ===
from transformers import TrainingArguments

training_arguments = TrainingArguments(
    output_dir=output_model,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    optim="paged_adamw_32bit",
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    num_train_epochs=3,
    logging_steps=10,
    save_strategy="epoch",
    save_total_limit=1,
    fp16=True,
    report_to="none",
)

# === SFT Trainer ===
from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    peft_config=peft_config,
    dataset_text_field="text",
    args=training_arguments,
    packing=False,
    max_seq_length=1024,
)

# === Start Training ===
trainer.train()

# === Save the Fine-tuned Model ===
trainer.save_model(output_model)
print(f"✅ Training complete. Model saved to {output_model}")

from google.colab import files
uploaded = files.upload()

# === Dataset ===
from datasets import load_dataset

dataset = load_dataset("json", data_files="formatted_tinyllama_dataset.json")
dataset = dataset["train"].train_test_split(test_size=0.1, seed=42)

# === Model + Tokenizer ===
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch

model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
output_model = "tinyllama-improm2prompt-v1"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
)
model.config.use_cache = False
model.config.pretraining_tp = 1

# === LoRA Configuration ===
from peft import LoraConfig

peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj"],
)

# === Training Arguments ===
from transformers import TrainingArguments

training_arguments = TrainingArguments(
    output_dir=output_model,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    optim="paged_adamw_32bit",
    learning_rate=2e-4,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    num_train_epochs=3,
    logging_steps=10,
    save_strategy="epoch",
    save_total_limit=1,
    fp16=True,
    report_to="none",
)

# === SFT Trainer ===
from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    peft_config=peft_config,
    dataset_text_field="text",
    args=training_arguments,
    packing=False,
    max_seq_length=1024,
)

# === Start Training ===
trainer.train()

# === Save the Fine-tuned Model ===
trainer.save_model(output_model)
print(f"✅ Training complete. Model saved to {output_model}")

from transformers import pipeline

# Load the fine-tuned model and tokenizer
model_dir = "tinyllama-improm2prompt-v1"

pipe = pipeline(
    "text-generation",
    model=model_dir,
    tokenizer=model_dir,
    torch_dtype=torch.float16,
    device_map="auto",
)

# === Test Prompts ===
prompts = [
    "Explain the concept of a stack data structure.",
    "Refine the following query into a clear instruction: how to find the shortest path in a graph?",
    "Describe the difference between merge sort and quick sort.",
]

for i, prompt in enumerate(prompts, 1):
    print(f"\n🧠 Prompt {i}: {prompt}\n")
    output = pipe(prompt, max_new_tokens=150, do_sample=True, temperature=0.7, top_p=0.9)
    print("💬 Model Response:", output[0]["generated_text"])

from transformers import pipeline

model_dir = "tinyllama-improm2prompt-v1"

pipe = pipeline(
    "text-generation",
    model=model_dir,
    tokenizer=model_dir,
    torch_dtype=torch.float16,
    device_map="auto",
)

# Helper: format prompt same way as training
def format_prompt(user_input):
    return f"<|user|>\n{user_input}</s>\n<|assistant|>\n"

# Test prompts
prompts = [
    "Explain the concept of a stack data structure.",
    "Refine the following query into a clear instruction: how to find the shortest path in a graph?",
    "Describe the difference between merge sort and quick sort.",
]

for i, prompt in enumerate(prompts, 1):
    print(f"\n🧠 Prompt {i}: {prompt}\n")
    formatted = format_prompt(prompt)
    output = pipe(formatted, max_new_tokens=150, do_sample=True, temperature=0.7, top_p=0.9)
    response = output[0]["generated_text"].split("<|assistant|>")[-1].strip()
    print("💬 Model Response:", response)

from transformers import pipeline

model_dir = "tinyllama-improm2prompt-v1"

pipe = pipeline(
    "text-generation",
    model=model_dir,
    tokenizer=model_dir,
    torch_dtype=torch.float16,
    device_map="auto",
)

# Function to generate refined prompts
def refine_prompt(raw_prompt):
    # Match the same structure as in training
    formatted = (
        "### Instruction:\n"
        "Refine the following user prompt into a precise, structured, and detailed version.\n\n"
        f"### Input:\n{raw_prompt}\n\n### Output:\n"
    )

    output = pipe(
        formatted,
        max_new_tokens=120,
        do_sample=True,
        temperature=0.7,
        top_p=0.9,
        eos_token_id=pipe.tokenizer.eos_token_id,
    )[0]["generated_text"]

    # Extract only the refined part
    if "### Output:" in output:
        refined = output.split("### Output:")[-1].strip()
    else:
        refined = output.strip()

    return refined

# === Test it ===
test_prompts = [
    "rag system",
    "difference between ai and ml",
    "importance of tokenization",
    "generate creative writing ideas",
    "how to fine-tune a model",
]

for p in test_prompts:
    refined = refine_prompt(p)
    print(f"\n🧠 Original: {p}\n✨ Refined:  {refined}\n{'-'*80}")

from transformers import pipeline
import torch

model_dir = "tinyllama-improm2prompt-v1"
pipe = pipeline(
    "text-generation",
    model=model_dir,
    tokenizer=model_dir,
    torch_dtype=torch.float16,
    device_map="auto",
)

def refine_prompt(raw_prompt, max_new_tokens=120):
    template = (
        "### Instruction:\n"
        "Refine the following user prompt into a precise, structured, and detailed version.\n\n"
        f"### Input:\n{raw_prompt}\n\n### Output:\n"
    )
    # Deterministic / higher-quality generation: beam search, no sampling
    out = pipe(
        template,
        max_new_tokens=max_new_tokens,
        do_sample=False,        # disable sampling
        num_beams=4,           # beam search
        early_stopping=True,
        return_full_text=False
    )[0]["generated_text"]

    # robust extraction: after "### Output:" until next section or EOS
    if "### Output:" in out:
        refined = out.split("### Output:")[-1].strip()
    else:
        # fallback: remove the prompt prefix
        refined = out.replace(template, "").strip()
    # stop at next "### Instruction" or after newline markers possibly added
    refined = refined.split("### Instruction:")[0].strip()
    return refined

tests = [
    "rag system",
    "difference between ai and ml",
    "importance of tokenization"
]
for t in tests:
    print("RAW:", t)
    print("REFINED:", refine_prompt(t))
    print("-"*60)

import json, random, re
path = "formatted_tinyllama_dataset.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

# Quick checks:
print("Total entries:", len(data))

# 1) find exact duplicates of input==output (those teach identity/equality)
dupe_same = [i for i, e in enumerate(data) if "### Input:" in e["text"] and e["text"].split("### Input:")[-1].strip()[:100] == e["text"].split("### Output:")[-1].strip()[:100]]
print("examples where Input and Output start the same (count):", len(dupe_same))

# 2) find outputs that look like UI prompts or ask for number inputs
bad_patterns = []
for i,e in enumerate(data):
    out = e["text"].split("### Output:")[-1].strip().lower()
    if re.search(r"please enter|enter the number|prompt:\s*enter|please provide your|press enter", out):
        bad_patterns.append((i,out[:150]))
print("ui-like outputs found:", len(bad_patterns))
print(bad_patterns[:10])

# 3) sample some entries for manual inspection
print("\nRandom samples for manual check:")
for i in random.sample(range(len(data)), min(10, len(data))):
    print("----")
    print(data[i]["text"][:300])

from transformers import pipeline
import torch

pipe = pipeline(
    "text-generation",
    model="tinyllama-improm2prompt-v1",
    tokenizer="tinyllama-improm2prompt-v1",
    torch_dtype=torch.float16,
    device_map="auto",
)

def refine_prompt(raw_prompt):
    template = (
        "### Instruction:\n"
        "Refine the following user prompt into a precise, structured, and detailed version.\n\n"
        f"### Input:\n{raw_prompt}\n\n### Output:\n"
    )
    output = pipe(
        template,
        max_new_tokens=80,
        do_sample=False,       # turn off randomness
        num_beams=5,           # beam search
        early_stopping=True,
        eos_token_id=pipe.tokenizer.eos_token_id,
        return_full_text=False,
    )[0]["generated_text"]

    # Extract just the output portion
    refined = output.split("### Output:")[-1].strip()
    refined = refined.split("### Instruction:")[0].strip()
    return refined

# Test
tests = [
    "rag system",
    "difference between ai and ml",
    "importance of tokenization",
    "generate creative writing ideas",
    "how to fine-tune a model"
]

for t in tests:
    print(f"\n🧠 Original: {t}\n✨ Refined: {refine_prompt(t)}\n{'-'*80}")

training_arguments = TrainingArguments(
    output_dir=output_model,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=1e-4,     # lower LR for better alignment
    num_train_epochs=5,     # 2 extra epochs
    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
)

from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    peft_config=peft_config,
    dataset_text_field="text",
    args=training_arguments,
    packing=False,
    max_seq_length=1024,
)

trainer.train()

!pip install -q wandb

from trl import SFTTrainer

training_arguments = TrainingArguments(
    output_dir=output_model,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=1e-4,
    num_train_epochs=5,
    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
    report_to="none",   # ✅ disables wandb cleanly
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    peft_config=peft_config,
    dataset_text_field="text",
    args=training_arguments,
    packing=False,
    max_seq_length=1024,
)

trainer.train()

trainer.save_model(output_model)
print(f"✅ Model saved to {output_model}")

from transformers import pipeline
import torch

pipe = pipeline(
    "text-generation",
    model="tinyllama-improm2prompt-v1",
    tokenizer="tinyllama-improm2prompt-v1",
    torch_dtype=torch.float16,
    device_map="auto",
)

def refine_prompt(raw_prompt):
    template = (
        "### Instruction:\n"
        "Refine the following user prompt into a precise, structured, and detailed version.\n\n"
        f"### Input:\n{raw_prompt}\n\n### Output:\n"
    )
    output = pipe(
        template,
        max_new_tokens=80,
        do_sample=False,   # deterministic
        num_beams=5,
        early_stopping=True,
        eos_token_id=pipe.tokenizer.eos_token_id,
        return_full_text=False,
    )[0]["generated_text"]
    refined = output.split("### Output:")[-1].strip().split("### Instruction:")[0].strip()
    return refined

# Try a few
prompts = [
    "rag system",
    "difference between ai and ml",
    "importance of tokenization",
    "generate creative writing ideas",
    "how to fine-tune a model",
]

for p in prompts:
    print(f"\n🧠 Original: {p}\n✨ Refined:  {refine_prompt(p)}\n{'-'*80}")

from transformers import pipeline
import torch

pipe = pipeline(
    "text-generation",
    model="tinyllama-improm2prompt-v1",
    tokenizer="tinyllama-improm2prompt-v1",
    torch_dtype=torch.float16,
    device_map="auto",
)
def refine_prompt(raw_prompt):
    template = (
        "### Instruction:\n"
        "You are a prompt-engineering assistant. "
        "Rewrite the given user prompt into a clear, structured, and detailed instruction "
        "related to AI, data structures, algorithms, or programming. "
        "Do NOT include questions, interactive steps, or literal actions.\n\n"
        f"### Input:\n{raw_prompt}\n\n### Output:\n"
    )
    output = pipe(
        template,
        max_new_tokens=100,
        do_sample=False,
        num_beams=8,
        early_stopping=True,
        eos_token_id=pipe.tokenizer.eos_token_id,
        return_full_text=False,
    )[0]["generated_text"]

    refined = output.split("### Output:")[-1].strip().split("### Instruction:")[0].strip()
    return refined

prompts = [
    "rag system",
    "difference between ai and ml",
    "importance of tokenization",
    "generate creative writing ideas",
    "how to fine-tune a model",
]

for p in prompts:
    print(f"\n🧠 Original: {p}\n✨ Refined:  {refine_prompt(p)}\n{'-'*80}")

from google.colab import files
uploaded = files.upload()

import json

with open("formatted_tinyllama_dataset.json") as f:
    base = json.load(f)
with open("refinement_dataset_v2_200.json") as f:
    add = json.load(f)

merged = base + add
with open("merged_refiner_dataset.json", "w") as f:
    json.dump(merged, f, indent=2)

# === Imports ===
import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import LoraConfig
from trl import SFTTrainer

# === Load merged dataset ===
dataset = load_dataset("json", data_files="merged_refiner_dataset.json")
dataset = dataset["train"].train_test_split(test_size=0.1, seed=42)

# === Model setup ===
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
output_model = "tinyllama-improm2prompt-v3"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
)
model.config.use_cache = False
model.config.pretraining_tp = 1

# === LoRA configuration ===
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj"],
)

# === Training arguments ===
training_arguments = TrainingArguments(
    output_dir=output_model,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=5e-5,   # lower LR for stable continued training
    num_train_epochs=2,   # just 2 epochs to "lock in" improvements
    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
    save_total_limit=1,
    report_to="none",     # disable wandb
)

# === Trainer ===
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    peft_config=peft_config,
    dataset_text_field="text",
    args=training_arguments,
    packing=False,
    max_seq_length=1024,
)

# === Train ===
trainer.train()

# === Save fine-tuned model ===
trainer.save_model(output_model)
print(f"✅ Retraining complete! Model saved to {output_model}")

from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="tinyllama-improm2prompt-v3",
    tokenizer="tinyllama-improm2prompt-v3",
    torch_dtype=torch.float16,
    device_map="auto",
)

def refine_prompt(raw_prompt):
    template = (
        "### Instruction:\n"
        "Refine the following user prompt into a precise, professional, and contextually rich instruction "
        "that could be used to guide an AI system. "
        "Focus on clarity and completeness — do NOT describe how to perform the task, "
        "just rewrite the prompt to make it clearer.\n\n"
        f"### Input:\n{raw_prompt}\n\n### Output:\n"
    )
    output = pipe(
        template,
        max_new_tokens=100,
        do_sample=False,
        num_beams=6,
        early_stopping=True,
        eos_token_id=pipe.tokenizer.eos_token_id,
        return_full_text=False,
    )[0]["generated_text"]

    refined = output.split("### Output:")[-1].strip().split("### Instruction:")[0].strip()
    return refined

# Test
prompts = [
    "rag system",
    "difference between ai and ml",
    "importance of tokenization",
    "graph traversal example",
    "dynamic programming explanation"
]

for p in prompts:
    print(f"\n🧠 Original: {p}\n✨ Refined: {refine_prompt(p)}\n{'-'*80}")

refine_prompt("how to implement bfs")

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/MyDrive/"

from google.colab import drive
drive.mount('/content/drive')

import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import LoraConfig
from trl import SFTTrainer

# === Load merged dataset ===
dataset = load_dataset("json", data_files="merged_refiner_dataset.json")
dataset = dataset["train"].train_test_split(test_size=0.1, seed=42)

# === Model setup ===
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
output_model = "tinyllama-improm2prompt-v3"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
)
model.config.use_cache = False

# === LoRA configuration ===
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj"],
)

# === Training arguments ===
training_arguments = TrainingArguments(
    output_dir=output_model,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=5e-5,
    num_train_epochs=2,
    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
    save_total_limit=1,
    report_to="none",
)

# === Trainer ===
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    peft_config=peft_config,
    dataset_text_field="text",
    args=training_arguments,
    packing=False,
    max_seq_length=1024,
)

# === Train ===
trainer.train()

# === Save model in Colab ===
trainer.save_model(output_model)
print("✅ Model saved in Colab")

!pip install -U transformers==4.44.2 trl==0.9.6 peft==0.10.0 accelerate==0.33.0 bitsandbytes==0.43.3

import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import LoraConfig
from trl import SFTTrainer

!nvcc --version

!pip uninstall -y bitsandbytes triton
!pip install bitsandbytes==0.43.2
!pip install triton==2.1.0

import bitsandbytes as bnb
print("GPU detected:", bnb.cuda_setup.is_available())

!pip uninstall -y bitsandbytes triton
!pip install bitsandbytes-cuda120==0.43.1
!pip install triton==2.1.0

!pip uninstall -y bitsandbytes triton
!pip install -U bitsandbytes==0.43.3 triton==2.3.0

import torch, bitsandbytes as bnb, sys, site, os, subprocess, importlib

print("Torch CUDA available:", torch.cuda.is_available())
print("Torch CUDA version (reported by nvcc):")
print(subprocess.getoutput("nvcc --version"))

# Quick attempt to import (may warn about missing libbitsandbytes_cuda126.so)
try:
    _ = bnb.__version__
    print("bitsandbytes version:", bnb.__version__)
except Exception as e:
    print("bitsandbytes import error:", e)

import bitsandbytes as bnb
print("GPU support:", bnb.cuda_setup.is_available())

import bitsandbytes as bnb
from bitsandbytes.cuda_setup import cuda_setup
print("GPU support:", cuda_setup.is_available())

from transformers import AutoModelForCausalLM, BitsAndBytesConfig

try:
    test_bnb = AutoModelForCausalLM.from_pretrained(
        "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
        quantization_config=BitsAndBytesConfig(load_in_4bit=True),
        device_map="auto",
    )
    print("✅ 4-bit quantization works — GPU support confirmed.")
except Exception as e:
    print("❌ 4-bit load failed. Error:")
    print(e)

from google.colab import drive
drive.mount('/content/drive')

from datasets import load_dataset
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments
from peft import LoraConfig
from trl import SFTTrainer

# Load dataset
dataset = load_dataset("json", data_files="merged_refiner_dataset.json")
dataset = dataset["train"].train_test_split(test_size=0.1, seed=42)

# Model ID + output folder
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
output_model = "tinyllama-improm2prompt-v3"

# 4-bit quantization config (correct version)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,   # ✅ Restored
)

# Load tokenizer + model
tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
)

model.config.use_cache = False
model.config.pretraining_tp = 1       # ✅ Restored

# LoRA config
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj"],
)

# Training settings (restored LR)
training_arguments = TrainingArguments(
    output_dir=output_model,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=5e-5,        # ✅ Restored learning rate
    num_train_epochs=2,
    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
    save_total_limit=1,
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    peft_config=peft_config,
    dataset_text_field="text",
    args=training_arguments,
    packing=False,
    max_seq_length=1024,
)

trainer.train()

from google.colab import files
uploaded = files.upload()

import json

with open("formatted_tinyllama_dataset.json") as f:
    base = json.load(f)
with open("refinement_dataset_v2_200.json") as f:
    add = json.load(f)

merged = base + add

with open("merged_refiner_dataset.json", "w") as f:
    json.dump(merged, f, indent=2)

print("✅ merged_refiner_dataset.json created successfully!")

!ls -lh merged_refiner_dataset.json

from datasets import load_dataset
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments
from peft import LoraConfig
from trl import SFTTrainer

# Load dataset
dataset = load_dataset("json", data_files="merged_refiner_dataset.json")
dataset = dataset["train"].train_test_split(test_size=0.1, seed=42)

# Model ID + output folder
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
output_model = "tinyllama-improm2prompt-v3"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
)

model.config.use_cache = False
model.config.pretraining_tp = 1

peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj"],
)

training_arguments = TrainingArguments(
    output_dir=output_model,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=5e-5,
    num_train_epochs=2,
    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
    save_total_limit=1,
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    peft_config=peft_config,
    dataset_text_field="text",
    args=training_arguments,
    packing=False,
    max_seq_length=1024,
)

trainer.train()

from google.colab import drive
drive.mount('/content/drive')

!cp -r /content/tinyllama-improm2prompt-v3 /content/drive/MyDrive/
print("✅ Model saved permanently to Google Drive!")

from transformers import pipeline

model_path = "/content/drive/MyDrive/tinyllama-improm2prompt-v3"

pipe = pipeline(
    "text-generation",
    model=model_path,
    tokenizer=model_path,
    torch_dtype="auto",
    device_map="auto",
)

!pip uninstall -y transformers trl peft accelerate

!pip install -U transformers==4.36.2
!pip install -U trl==0.7.10
!pip install -U peft==0.8.2
!pip install -U accelerate==0.25.0

from transformers import pipeline

model_path = "/content/drive/MyDrive/tinyllama-improm2prompt-v3"

pipe = pipeline(
    "text-generation",
    model=model_path,
    tokenizer=model_path,
    device_map="auto",
    torch_dtype="auto",
)

!ls -R "/content/drive/MyDrive/tinyllama-improm2prompt-v3"

!pip install -U transformers==4.36.2 peft==0.8.2 trl==0.7.10 accelerate==0.25.0

from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
lora_path = "/content/drive/MyDrive/tinyllama-improm2prompt-v3/checkpoint-126"

# Load tokenizer from base model
tokenizer = AutoTokenizer.from_pretrained(base_model)
tokenizer.pad_token = tokenizer.eos_token

# Load base model + apply LoRA adapter
model = AutoPeftModelForCausalLM.from_pretrained(
    lora_path,
    device_map="auto",
    torch_dtype=torch.float16,
)

# Merge LoRA weights into the base model permanently
model = model.merge_and_unload()

!pip install -U peft==0.10.0

from transformers import AutoTokenizer
from peft import AutoPeftModelForCausalLM

base_model = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
lora_path = "/content/drive/MyDrive/tinyllama-improm2prompt-v3/checkpoint-126"

tokenizer = AutoTokenizer.from_pretrained(base_model)
tokenizer.pad_token = tokenizer.eos_token

model = AutoPeftModelForCausalLM.from_pretrained(
    lora_path,
    device_map="auto",
    torch_dtype="auto",
)

model = model.merge_and_unload()

save_path = "/content/drive/MyDrive/tinyllama-improm2prompt-v3-MERGED"

model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)

print("✅ Fully merged model saved at:", save_path)

from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model=save_path,
    tokenizer=save_path,
    device_map="auto",
    torch_dtype="auto",
)

import torch
from transformers import pipeline

save_path = "/content/drive/MyDrive/tinyllama-improm2prompt-v3-MERGED"   # ✅ full merged model folder

pipe = pipeline(
    "text-generation",
    model=save_path,
    tokenizer=save_path,
    torch_dtype=torch.float16,
    device_map="auto",
)

def refine_prompt(raw_prompt):
    template = (
        "### Instruction:\n"
        "Refine the following user prompt into a precise, professional, and contextually rich instruction "
        "that could be used to guide an AI system. "
        "Focus on clarity and completeness — do NOT describe how to perform the task, "
        "just rewrite the prompt to make it clearer.\n\n"
        f"### Input:\n{raw_prompt}\n\n### Output:\n"
    )

    output = pipe(
        template,
        max_new_tokens=100,
        do_sample=False,
        num_beams=6,
        early_stopping=True,
        eos_token_id=pipe.tokenizer.eos_token_id,
        return_full_text=False,
    )[0]["generated_text"]

    refined = output.strip()
    return refined


# ✅ Test
prompts = [
    "rag system",
    "difference between ai and ml",
    "importance of tokenization",
    "graph traversal example",
    "dynamic programming explanation"
]

for p in prompts:
    print(f"\n🧠 Original: {p}\n✨ Refined: {refine_prompt(p)}\n{'-'*80}")

from transformers import pipeline
import torch

save_path = "/content/drive/MyDrive/tinyllama-improm2prompt-v3-MERGED"  # merged model folder

pipe = pipeline(
    "text-generation",
    model=save_path,
    tokenizer=save_path,
    torch_dtype=torch.float16,
    device_map="auto",
)

FEWSHOT = (
    "### Instruction:\n"
    "Refine the following user prompt into a precise, professional, and contextually rich instruction "
    "for an AI system. Do NOT give steps or answers—only rewrite the prompt.\n\n"

    # 1) AI example
    "### Input:\nrag system\n\n"
    "### Output:\nExplain the architecture and workflow of a Retrieval-Augmented Generation (RAG) system, "
    "including how the retriever selects relevant documents and how the generator integrates retrieved context into its response.\n\n"

    # 2) DSA example
    "### Input:\nbinary search tree\n\n"
    "### Output:\nDescribe the properties and core operations of a Binary Search Tree (BST)—insertion, search, and in-order traversal—with a concise illustrative example.\n\n"

    # 3) DSA example
    "### Input:\ndynamic programming example\n\n"
    "### Output:\nFormulate a clear instruction that requests a dynamic-programming solution outline, including subproblem definition, recurrence relation, and base cases, using a representative problem (e.g., coin change or LIS).\n\n"
)

def refine_prompt(raw_prompt: str) -> str:
    prompt = (
        FEWSHOT +
        f"### Input:\n{raw_prompt}\n\n### Output:\n"
    )
    out = pipe(
        prompt,
        max_new_tokens=96,
        do_sample=False,          # deterministic
        num_beams=6,              # search for best non-generic continuation
        length_penalty=0.9,
        early_stopping=True,
        no_repeat_ngram_size=3,   # reduce boilerplate loops
        return_full_text=False,
        eos_token_id=pipe.tokenizer.eos_token_id,
    )[0]["generated_text"].strip()

    # Post-clean: stop if model drifts back into a new "###" section
    out = out.split("### Instruction:")[0].strip()

    # If it still returns a meta sentence, try a second pass with a tighter one-shot
    if out.lower().startswith("refine the user prompt") or out.lower().startswith("write a clear, structured"):
        one_shot = (
            "### Instruction:\nRewrite the prompt so it becomes a concrete, domain-specific instruction. "
            "No steps, no answers—just the improved instruction.\n\n"
            f"### Input:\n{raw_prompt}\n\n### Output:\n"
        )
        out2 = pipe(
            one_shot,
            max_new_tokens=80,
            do_sample=False,
            num_beams=8,
            no_repeat_ngram_size=3,
            return_full_text=False,
            eos_token_id=pipe.tokenizer.eos_token_id,
        )[0]["generated_text"].strip()
        out2 = out2.split("### Instruction:")[0].strip()
        if len(out2) > 0:
            out = out2
    return out

!ls "/content/drive/MyDrive/tinyllama-improm2prompt-v3-MERGED"

from google.colab import drive
drive.mount('/content/drive')

!ls "/content/drive/MyDrive/tinyllama-improm2prompt-v3-MERGED"

save_path = "/content/drive/MyDrive/tinyllama-improm2prompt-v3-MERGED"

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
import torch

tokenizer = AutoTokenizer.from_pretrained(save_path, local_files_only=True)
model = AutoModelForCausalLM.from_pretrained(
    save_path,
    torch_dtype=torch.float16,
    device_map="auto",
    local_files_only=True,
)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.float16,
    device_map="auto",
)

def refine_prompt(raw_prompt):
    prompt = (
        "Rewrite the following prompt so that it becomes a clearer, more specific instruction. "
        "Do NOT answer it, only rewrite it.\n\n"
        f"Original Prompt: {raw_prompt}\n"
        "Refined Prompt:"
    )

    result = pipe(prompt, max_new_tokens=80, do_sample=False)[0]["generated_text"]
    return result.replace(prompt, "").strip()

refine_prompt("bfs")

def refine_prompt(raw_prompt):
    template = (
        # === Few-shot examples to guide refinement ===
        "### Instruction:\n"
        "Refine the following user prompt into a precise, professional, and contextually rich instruction "
        "that could be used to guide an AI system. "
        "Focus on clarity and completeness — do NOT describe how to perform the task, "
        "just rewrite the prompt to make it clearer.\n\n"

        "### Input:\nrag system\n\n"
        "### Output:\nExplain the structure and workflow of a Retrieval-Augmented Generation (RAG) system, "
        "including how external knowledge retrieval is integrated into the generation process.\n\n"

        "### Input:\ndifference between ai and ml\n\n"
        "### Output:\nExplain the conceptual and functional differences between Artificial Intelligence (AI) "
        "and Machine Learning (ML), highlighting how ML fits as a subset within AI.\n\n"

        "### Input:\nimportance of tokenization\n\n"
        "### Output:\nDescribe the role of tokenization in natural language processing, "
        "including how text is segmented into meaningful units and why this step impacts model accuracy.\n\n"

        # === Your actual input goes here ===
        f"### Input:\n{raw_prompt}\n\n### Output:\n"
    )

    output = pipe(
        template,
        max_new_tokens=120,
        do_sample=False,
        num_beams=6,
        early_stopping=True,
        eos_token_id=pipe.tokenizer.eos_token_id,
        return_full_text=False,
    )[0]["generated_text"]

    refined = (
        output.split("### Output:")[-1]
        .split("### Instruction:")[0]
        .strip()
    )
    return refined

refine_prompt("bfs")

from google.colab import drive
drive.mount('/content/drive')

save_path = "/content/drive/MyDrive/tinyllama-improm2prompt-v3-MERGED"

model_path = "/content/drive/MyDrive/tinyllama-improm2prompt-v3-MERGED"

from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import torch

tokenizer = AutoTokenizer.from_pretrained(model_path, local_files_only=True)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.float16,
    device_map="auto",
    local_files_only=True,
)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.float16,
    device_map="auto",
)

def refine_prompt(raw_prompt):
    template = (
        "### Instruction:\n"
        "Refine the following user prompt into a precise, professional, and contextually rich instruction "
        "that could be used to guide an AI system. "
        "Focus on clarity and completeness — do NOT describe how to perform the task, "
        "just rewrite the prompt to make it clearer.\n\n"

        "### Input:\nrag system\n\n"
        "### Output:\nExplain the architecture and workflow of a Retrieval-Augmented Generation (RAG) system, "
        "detailing how external knowledge retrieval is integrated into the response generation pipeline.\n\n"

        "### Input:\ndifference between ai and ml\n\n"
        "### Output:\nDescribe the conceptual and practical distinctions between Artificial Intelligence (AI) "
        "and Machine Learning (ML), noting the hierarchical relationship between the two.\n\n"

        "### Input:\nimportance of tokenization\n\n"
        "### Output:\nExplain the significance of tokenization in natural language processing, including how "
        "text is segmented into interpretable units and why this affects model understanding and accuracy.\n\n"

        f"### Input:\n{raw_prompt}\n\n### Output:\n"
    )

    output = pipe(
        template,
        max_new_tokens=120,
        do_sample=False,
        num_beams=6,
        early_stopping=True,
        return_full_text=False,
        eos_token_id=pipe.tokenizer.eos_token_id,
    )[0]["generated_text"]

    refined = output.split("### Output:")[-1].split("### Instruction:")[0].strip()
    return refined

print(refine_prompt("bfs"))

print(refine_prompt("greedy algorithm"))

print(refine_prompt("rag system"))

print(refine_prompt("array"))

print(refine_prompt("infix expression"))

from google.colab import drive
drive.mount('/content/drive')

model_path = "/content/drive/MyDrive/tinyllama-improm2prompt-v3-MERGED"

from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import torch

tokenizer = AutoTokenizer.from_pretrained(model_path, local_files_only=True)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.float16,
    device_map="auto",
    local_files_only=True,
)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.float16,
    device_map="auto",
)

def refine_prompt(raw_prompt):
    template = (
        "### Instruction:\n"
        "Refine the following user prompt into a precise, professional, and contextually rich instruction "
        "that could be used to guide an AI system. "
        "Focus on clarity and completeness — do NOT describe how to perform the task, "
        "just rewrite the prompt to make it clearer.\n\n"

        "### Input:\nrag system\n\n"
        "### Output:\nExplain the architecture and workflow of a Retrieval-Augmented Generation (RAG) system, "
        "detailing how external knowledge retrieval is integrated into the response generation pipeline.\n\n"

        "### Input:\ndifference between ai and ml\n\n"
        "### Output:\nDescribe the conceptual and practical distinctions between Artificial Intelligence (AI) "
        "and Machine Learning (ML), noting the hierarchical relationship between the two.\n\n"

        "### Input:\nimportance of tokenization\n\n"
        "### Output:\nExplain the significance of tokenization in natural language processing, including how "
        "text is segmented into interpretable units and why this affects model understanding and accuracy.\n\n"

        f"### Input:\n{raw_prompt}\n\n### Output:\n"
    )

    output = pipe(
        template,
        max_new_tokens=120,
        do_sample=False,
        num_beams=6,
        early_stopping=True,
        return_full_text=False,
        eos_token_id=pipe.tokenizer.eos_token_id,
    )[0]["generated_text"]

    refined = output.split("### Output:")[-1].split("### Instruction:")[0].strip()
    return refined

print(refine_prompt("bfs"))

def show_refinement(prompt):
    refined = refine_prompt(prompt)
    print(f"🧠 Original: {prompt}\n✨ Refined: {refined}\n" + "-"*80)

def run_refiner():
    while True:
        user_input = input("Enter a prompt to refine (or type 'exit' to stop): ")

        if user_input.lower().strip() in ["exit", "quit", "q"]:
            print("👋 Exiting Prompt Refiner. Have a great day!")
            break

        show_refinement(user_input)

run_refiner()

from google.colab import drive
drive.mount('/content/drive')

model_path = "/content/drive/MyDrive/tinyllama-improm2prompt-v3-MERGED"

from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import torch

tokenizer = AutoTokenizer.from_pretrained(model_path, local_files_only=True)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.float16,
    device_map="auto",
    local_files_only=True,
)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.float16,
    device_map="auto",
)

def refine_prompt(raw_prompt):
    template = (
        "### Instruction:\n"
        "Refine the following user prompt into a precise, professional, and contextually rich instruction "
        "that could be used to guide an AI system. "
        "Focus on clarity and completeness — do NOT describe how to perform the task, "
        "just rewrite the prompt to make it clearer.\n\n"

        "### Input:\nrag system\n\n"
        "### Output:\nExplain the architecture and workflow of a Retrieval-Augmented Generation (RAG) system, "
        "detailing how external knowledge retrieval is integrated into the response generation pipeline.\n\n"

        "### Input:\ndifference between ai and ml\n\n"
        "### Output:\nDescribe the conceptual and practical distinctions between Artificial Intelligence (AI) "
        "and Machine Learning (ML), noting the hierarchical relationship between the two.\n\n"

        "### Input:\nimportance of tokenization\n\n"
        "### Output:\nExplain the significance of tokenization in natural language processing, including how "
        "text is segmented into interpretable units and why this affects model understanding and accuracy.\n\n"

        f"### Input:\n{raw_prompt}\n\n### Output:\n"
    )

    output = pipe(
        template,
        max_new_tokens=120,
        do_sample=False,
        num_beams=6,
        early_stopping=True,
        return_full_text=False,
        eos_token_id=pipe.tokenizer.eos_token_id,
    )[0]["generated_text"]

    refined = output.split("### Output:")[-1].split("### Instruction:")[0].strip()
    return refined

def show_refinement(prompt):
    refined = refine_prompt(prompt)
    print(f"🧠 Original: {prompt}\n✨ Refined: {refined}\n" + "-"*80)

def run_refiner():
    while True:
        user_input = input("Enter a prompt to refine (or type 'exit' to stop): ")

        if user_input.lower().strip() in ["exit", "quit", "q"]:
            print("👋 Exiting Prompt Refiner. Have a great day!")
            break

        show_refinement(user_input)

run_refiner()